export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_GOOGLE_REQUEST = "GET_GOOGLE_REQUEST";
export const GET_GOOGLE_SUCCESS = "GET_GOOGLE_SUCCESS";
export const GET_GOOGLE_FAILURE = "GET_GOOGLE_FAILURE";







